# Generated by Django 3.0.7 on 2020-08-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_register', '0002_auto_20200804_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ba_no',
            field=models.CharField(max_length=100),
        ),
    ]
