# Generated by Django 3.0.7 on 2020-09-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(max_length=100)),
                ('vendor_name', models.CharField(max_length=100)),
                ('service_provided', models.CharField(choices=[('Recharges', 'Recharges'), ('Electricity', 'Electricity'), ('Building Rent', 'Building Rent'), ('Water Supply', 'Water Supply')], default='Recharges', max_length=100)),
                ('cost', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('payment_duration', models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Fourthnight', 'Fourthnight')], default='Weekly', max_length=100)),
                ('mode_of_pay', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Online', 'Online')], default='Cash', max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('vendor_pan', models.CharField(max_length=100)),
                ('vendor_gst', models.CharField(max_length=100)),
                ('type_amt', models.CharField(choices=[('Fixed', 'Fixed'), ('Variable', 'Variable')], default='Fixed', max_length=100)),
                ('amt', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('acc_no', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
