# Generated by Django 3.0.7 on 2020-09-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='amt_paid',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='pay_status',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
