# Generated by Django 3.0.7 on 2020-09-09 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20200908_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='amt_paid',
        ),
    ]
