# Generated by Django 3.0.7 on 2020-09-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_vendor_amt_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='time',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
