# Generated by Django 3.0.7 on 2020-09-09 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_vendor_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='date',
            new_name='paid_date',
        ),
    ]
