# Generated by Django 3.0.7 on 2020-09-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_auto_20200910_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='taxpayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('receipt_id', models.CharField(max_length=100)),
                ('sgst', models.CharField(max_length=100)),
                ('cgst', models.CharField(max_length=100)),
                ('tax', models.CharField(max_length=100)),
            ],
        ),
    ]
