# Generated by Django 3.0.7 on 2020-09-10 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_taxpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='amount_paid',
        ),
    ]
