# Generated by Django 3.0.7 on 2020-08-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='from_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Earned', 'Earned/Previledge Leave'), ('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('other', 'Other leave')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='leave',
            name='numdays',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='to_date',
            field=models.DateField(blank=True),
        ),
    ]
