# Generated by Django 3.0.7 on 2020-08-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20200815_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Earned', 'Earned/Previledge Leave'), ('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('other', 'Other leave')], max_length=50),
        ),
        migrations.AlterField(
            model_name='leave',
            name='numdays',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='leave',
            name='to_date',
            field=models.DateField(),
        ),
    ]
