# Generated by Django 3.0.7 on 2020-08-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_auto_20200815_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('otp', models.IntegerField()),
            ],
        ),
    ]
