# Generated by Django 3.0.7 on 2020-08-29 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0013_auto_20200813_2142'),
        ('hr', '0006_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='salaryemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_generate', models.DateField(auto_now_add=True)),
                ('emp_name', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('present_days', models.IntegerField()),
                ('sal', models.CharField(max_length=100)),
                ('working_days', models.CharField(max_length=100)),
                ('gross', models.CharField(max_length=100)),
                ('pf', models.CharField(max_length=100)),
                ('esi', models.CharField(max_length=100)),
                ('it', models.CharField(max_length=100)),
                ('total_dedu', models.CharField(max_length=100)),
                ('payable', models.CharField(max_length=100)),
                ('emid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpage.addemployee')),
            ],
        ),
    ]
