# Generated by Django 3.0.7 on 2020-08-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_auto_20200830_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryemp',
            name='dept',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salaryemp',
            name='emp_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salaryemp',
            name='sal',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salaryemp',
            name='emid',
            field=models.CharField(max_length=100),
        ),
    ]
