# Generated by Django 3.0.7 on 2020-08-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_auto_20200830_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryemp',
            name='basic_pay',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salaryemp',
            name='hra',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salaryemp',
            name='special_allowance',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
