# Generated by Django 3.0.7 on 2020-09-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_auto_20200830_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryemp',
            name='status',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
