# Generated by Django 3.0.7 on 2020-09-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_salmonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryemp',
            name='month',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
