# Generated by Django 3.0.7 on 2020-09-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_salaryemp_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryemp',
            name='account_no',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
