# Generated by Django 3.0.7 on 2020-09-07 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_salaryemp_account_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaryemp',
            old_name='account_no',
            new_name='acno',
        ),
    ]
