# Generated by Django 3.0.7 on 2020-09-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientid', models.CharField(max_length=100)),
                ('clientname', models.CharField(max_length=100)),
                ('client_address', models.CharField(max_length=500)),
                ('company_name', models.CharField(max_length=500)),
                ('contact', models.CharField(max_length=10)),
                ('alcontact', models.CharField(max_length=10)),
                ('company_email', models.EmailField(max_length=254)),
                ('meeting', models.CharField(choices=[('ERP', 'ERP'), ('CRM', 'CRM'), ('Billing', 'Billing'), ('Ecommerce', 'Ecommerce'), ('HRM', 'HRM')], default='ERP', max_length=100)),
                ('remarks', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('Opened', 'Opened'), ('Closed', 'Closed')], default='Opened', max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('empname', models.CharField(max_length=100)),
                ('quotation', models.CharField(max_length=100)),
                ('empid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Emp_Quot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_id', models.CharField(max_length=100)),
                ('client_id', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=100)),
                ('first_payment_date', models.DateField()),
                ('reason', models.TextField()),
                ('client_deadline', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('first_amt', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('discount', models.CharField(max_length=100)),
                ('tax', models.CharField(max_length=100)),
                ('subtotal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='services_quot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=100)),
                ('quotation_id', models.CharField(max_length=100)),
                ('service_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('no_of_units', models.IntegerField()),
                ('tax_percent', models.CharField(max_length=100)),
            ],
        ),
    ]
