# Generated by Django 3.0.7 on 2020-09-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_services_quot_technology'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp_quot',
            old_name='client_id',
            new_name='clientid',
        ),
        migrations.AddField(
            model_name='services_quot',
            name='clientid',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
