# Generated by Django 3.0.7 on 2020-09-07 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_auto_20200906_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_quot',
            name='client_deadline',
        ),
    ]
