# Generated by Django 3.0.7 on 2020-09-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_auto_20200907_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_quot',
            name='balance',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
