# Generated by Django 3.0.7 on 2020-09-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0011_auto_20200911_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_quot',
            name='work',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
