# Generated by Django 3.0.7 on 2020-09-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0012_emp_quot_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_quot',
            name='accept',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
