# Generated by Django 3.0.7 on 2020-09-12 06:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0013_emp_quot_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_quot',
            name='date_of_complete',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
