# Generated by Django 3.0.7 on 2020-09-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0014_emp_quot_date_of_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='total',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
