# Generated by Django 3.0.7 on 2020-08-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addemployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('full_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField()),
                ('aadhar', models.BigIntegerField()),
                ('pan', models.BigIntegerField()),
                ('whrs', models.IntegerField()),
                ('oemail', models.EmailField(max_length=254)),
                ('pemail', models.EmailField(max_length=254)),
                ('designation', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('doj', models.DateField()),
                ('address', models.TextField()),
                ('job_loc', models.TextField()),
                ('bank_name', models.CharField(max_length=100)),
                ('ba_no', models.BigIntegerField()),
                ('pfno', models.BigIntegerField()),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
