# Generated by Django 3.0.7 on 2020-08-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addemployee',
            name='password',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addemployee',
            name='username',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addemployee',
            name='aadhar',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='addemployee',
            name='contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='addemployee',
            name='pan',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='addemployee',
            name='pfno',
            field=models.CharField(max_length=25),
        ),
    ]
