# Generated by Django 3.0.7 on 2020-08-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0002_auto_20200804_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='addemployee',
            name='Employee_id',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
