# Generated by Django 3.0.7 on 2020-08-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0003_addemployee_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis_per', models.IntegerField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=100)),
                ('service_name', models.CharField(choices=[('Window', 'Window Application'), ('Web', 'Web Application'), ('Network', 'Network Application'), ('Mobile', 'Mobile Application')], default='window', max_length=100)),
                ('category', models.CharField(choices=[('ERP', 'ERP'), ('CRM', 'CRM'), ('Billing', 'Billing'), ('eCommerce', 'eCommerce'), ('HRM', 'HRM')], default='ERP', max_length=100)),
                ('cost', models.IntegerField()),
                ('technology', models.CharField(choices=[('Python', 'Python'), ('Php', 'Php'), ('Java', 'Java'), ('DotNet', 'DotNet')], default='Python', max_length=100)),
            ],
        ),
    ]
