# Generated by Django 3.0.7 on 2020-08-05 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0004_discount_mymodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='addservices',
        ),
    ]
