# Generated by Django 3.0.7 on 2020-08-06 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0005_auto_20200805_2226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addservices',
            new_name='add_services',
        ),
    ]
