# Generated by Django 3.0.7 on 2020-08-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0007_auto_20200806_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='serviceid',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
