# Generated by Django 3.0.7 on 2020-08-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0009_auto_20200806_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceid', models.CharField(max_length=100)),
                ('service_name', models.CharField(choices=[('Window', 'Window Application'), ('Web', 'Web Application'), ('Network', 'Network Application'), ('Mobile', 'Mobile Application')], default='window', max_length=100)),
                ('category', models.CharField(choices=[('ERP', 'ERP'), ('CRM', 'CRM'), ('Billing', 'Billing'), ('eCommerce', 'eCommerce'), ('HRM', 'HRM')], default='ERP', max_length=100)),
                ('cost', models.IntegerField()),
                ('technology', models.CharField(choices=[('Python', 'Python'), ('Php', 'Php'), ('Java', 'Java'), ('DotNet', 'DotNet')], default='Python', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='addservices',
        ),
    ]
