# Generated by Django 3.0.7 on 2020-08-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0012_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addemployee',
            name='image',
            field=models.ImageField(default='pics/person.png', upload_to='pics'),
        ),
    ]
