# Generated by Django 3.0.7 on 2020-09-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0014_auto_20200904_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addemployee',
            name='dept',
            field=models.CharField(choices=[('Human Resource', 'Human Resource'), ('Technical', 'Technical'), ('Marketing', 'Marketing'), ('Finance', 'Finance')], default='Human Resource', max_length=100),
        ),
    ]
