# Generated by Django 3.0.7 on 2020-09-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0015_auto_20200904_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='addemployee',
            name='msg',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
